version: '3.5'

services:

  sample:
    build:
      context: .
      args:
        MAXMIND_LICENSE_KEY: ''
    ports:
      - 3000:3000
    environment:
      - LOG_LEVEL=info
  nginx-cache-proxy:
    image: flaviostutz/nginx-cache-proxy
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PROXY_PASS_URL=http://sample:3000/